In [63]:
import graphlab
import numpy as np
from __future__ import division

In [2]:
sales = graphlab.SFrame("E:\\Machine Learning\\U.W\\Regression\\kc_house_data.gl/")

This non-commercial license of GraphLab Create for academic use is assigned to lxn1021@gmail.com and will expire on November 18, 2019.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: C:\Users\Xiaoning\AppData\Local\Temp\graphlab_server_1545047766.log.0


In [3]:
sales.head()

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	int
	floors	str
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 10

Data:
+------------+---------------------------+-----------+----------+-----------+
|     id     |            date           |   price   | bedrooms | bathrooms |
+------------+---------------------------+-----------+----------+-----------+
| 7129300520 | 2014-10-13 00:00:00+00:00 |  221900.0 |   3.0    |    1.0    |
| 6414100192 | 2014-12-09 00:00:00+00:00 |  538000.0 |   3.0    |    2.25   |
| 5631500400 | 2015-02-25 00:00:00+00:00 |  180000.0 |   2.0    |    1.0    |
| 2487200875 | 2014-12-09 00:00:00+00:00 |  604000.0 |   4.0    |    3.0    |
| 1954400510 | 2015-02-18 00:00:00+00:00 |  510000.0 |   3.0    |    2.0    |
| 7237550310 | 2014-05-12 00:00:00+00:00 | 1225000.0 |   4.0    |    4.5    |
| 1321400060 | 2014-06-27 00:00:00+00:00 |  257500.0 |   3.0    |    2.25   |
| 2008000270 | 2015-01-15 00:00:00+00:00 |  291850.0 |   3.0    |    1.5    |
| 2414600126 | 2015-04-15 00:00:00+00:00 |  229500.0 |   3.0    |    1.0    |
| 3793500160 | 2015-03-12 00:00:00+00:00 |  323000.0 |   3.0    |    2.5    |
+------------+---------------------------+-----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+------------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade | sqft_above |
+-------------+----------+--------+------------+------+-----------+-------+------------+
|    1180.0   |   5650   |   1    |     0      |  0   |     3     |   7   |    1180    |
|    2570.0   |   7242   |   2    |     0      |  0   |     3     |   7   |    2170    |
|    770.0    |  10000   |   1    |     0      |  0   |     3     |   6   |    770     |
|    1960.0   |   5000   |   1    |     0      |  0   |     5     |   7   |    1050    |
|    1680.0   |   8080   |   1    |     0      |  0   |     3     |   8   |    1680    |
|    5420.0   |  101930  |   1    |     0      |  0   |     3     |   11  |    3890    |
|    1715.0   |   6819   |   2    |     0      |  0   |     3     |   7   |    1715    |
|    1060.0   |   9711   |   1    |     0      |  0   |     3     |   7   |    1060    |
|    1780.0   |   7470   |   1    |     0      |  0   |     3     |   7   |    1050    |
|    1890.0   |   6560   |   2    |     0      |  0   |     3     |   7   |    1890    |
+-------------+----------+--------+------------+------+-----------+-------+------------+
+---------------+----------+--------------+---------+-------------+
| sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+---------------+----------+--------------+---------+-------------+
|       0       |   1955   |      0       |  98178  | 47.51123398 |
|      400      |   1951   |     1991     |  98125  | 47.72102274 |
|       0       |   1933   |      0       |  98028  | 47.73792661 |
|      910      |   1965   |      0       |  98136  |   47.52082  |
|       0       |   1987   |      0       |  98074  | 47.61681228 |
|      1530     |   2001   |      0       |  98053  | 47.65611835 |
|       0       |   1995   |      0       |  98003  | 47.30972002 |
|       0       |   1963   |      0       |  98198  | 47.40949984 |
|      730      |   1960   |      0       |  98146  | 47.51229381 |
|       0       |   2003   |      0       |  98038  | 47.36840673 |
+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -122.25677536 |     1340.0    | ... |
|  -122.3188624 |     1690.0    | ... |
| -122.23319601 |     2720.0    | ... |
| -122.39318505 |     1360.0    | ... |
| -122.04490059 |     1800.0    | ... |
| -122.00528655 |     4760.0    | ... |
| -122.32704857 

In [4]:
sales["floors"] = sales["floors"].astype(int)

In [5]:
def get_numpy_data(data_sframe, features, output):
    data_sframe["constant"] = 1
    features = ["constant"] + features
    features_sframe = data_sframe[features]
    
    feature_matrix = features_sframe.to_numpy()
    
    output_sarray = data_sframe[output]
    output_array = output_sarray.to_numpy()
    
    
    return (feature_matrix, output_array)

In [6]:
def predict_output(feature_matrix, weights):
    predictions = np.dot(feature_matrix, weights)
    
    return predictions

In [7]:
X = np.array([[3, 5, 8], [4, 12, 15]])

print X

[[ 3  5  8]
 [ 4 12 15]]


In [8]:
norms = np.linalg.norm(X, axis = 0)

print norms

[ 5. 13. 17.]


In [9]:
print X / norms

[[0.6        0.38461538 0.47058824]
 [0.8        0.92307692 0.88235294]]


In [10]:
def normalize_features(feature_matrix):
    norms = np.linalg.norm(feature_matrix, axis = 0)
    normalized_features = feature_matrix / norms
        
    return (normalized_features, norms)

In [11]:
features, norms = normalize_features(np.array([[3.,6.,9.],[4.,8.,12.]]))
print features
print norms

[[0.6 0.6 0.6]
 [0.8 0.8 0.8]]
[ 5. 10. 15.]


In [12]:
simple_features = ["sqft_living", "bedrooms"]
my_output = "price"
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)

In [13]:
simple_feature_matrix, norms = normalize_features(simple_feature_matrix)

In [14]:
weights = np.array([1, 4, 1])

In [15]:
prediction = predict_output(simple_feature_matrix, weights)

In [16]:
prediction

array([0.02675867, 0.04339256, 0.01990703, ..., 0.02289873, 0.03178473,
       0.02289873])

In [19]:
output - prediction

array([221899.97324133, 537999.95660744, 179999.98009297, ...,
       402100.97710127, 399999.96821527, 324999.97710127])

In [20]:
simple_feature_matrix

array([[0.00680209, 0.00353021, 0.00583571],
       [0.00680209, 0.00768869, 0.00583571],
       [0.00680209, 0.00230361, 0.00389048],
       ...,
       [0.00680209, 0.00305154, 0.00389048],
       [0.00680209, 0.00478673, 0.00583571],
       [0.00680209, 0.00305154, 0.00389048]])

In [21]:
weights

array([1, 4, 1])

In [43]:
(np.multiply(simple_feature_matrix[:, 1], output - prediction + np.multiply(weights[1], simple_feature_matrix[:, 1]))).sum()

87939470.77299108

In [44]:
ro = np.zeros(len(weights))

for i in range(len(ro)):
    ro[i] = (np.multiply(simple_feature_matrix[:, i], output - prediction + np.multiply(weights[i], simple_feature_matrix[:, i]))).sum()

1. Question 1
From the section "Effect of L1 penalty": Consider the simple model with 2 features trained on the entire sales dataset.

Which of the following values of l1_penalty would not set w[1] zero, but would set w[2] to zero, if we were to take a coordinate gradient step in that coordinate? (Select all that apply)

2. Question 2
Refer to the same model as the previous question.

Which of the following values of l1_penalty would set both w[1] and w[2] to zero, if we were to take a coordinate gradient step in that coordinate? (Select all that apply)

In [45]:
ro

array([79400300.03492916, 87939470.77299108, 80966698.67596565])

In [72]:
def lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty):
    prediction = predict_output(feature_matrix, weights)
    ro_i = (np.multiply(feature_matrix[:, i], output - prediction + np.multiply(weights[i], feature_matrix[:, i]))).sum()
    
    if i == 0:
        new_weight_i = ro_i
    elif ro_i < -l1_penalty / 2:
        new_weight_i = ro_i + l1_penalty / 2
    elif ro_i > l1_penalty / 2:
        new_weight_i = ro_i - l1_penalty / 2
    else:
        new_weight_i = 0
        
    return new_weight_i

In [73]:
import math
print lasso_coordinate_descent_step(1, np.array([[3./math.sqrt(13),1./math.sqrt(10)],[2./math.sqrt(13),3./math.sqrt(10)]]), 
                                   np.array([1., 1.]), np.array([1., 4.]), 0.1)

0.4255588466910251


In [81]:
def lasso_cyclical_coordinate_descent(feature_matrix, output, initial_weights, l1_penalty, tolerance):
    weights = initial_weights
    change = np.zeros(len(weights))
    
    for i in range(len(weights)):
        old_weights_i = weights[i]
        weights[i] = lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
        change[i] = weights[i] - old_weights_i
    
    max_change = max(change)
    if max_change >= tolerance:
        lasso_cyclical_coordinate_descent(feature_matrix, output, weights, l1_penalty, tolerance)
    
    
    return weights

In [75]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
initial_weights = np.zeros(3)
l1_penalty = 1e7
tolerance = 1.0

In [76]:
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)
(normalized_simple_feature_matrix, simple_norms) = normalize_features(simple_feature_matrix)

In [82]:
weights = lasso_cyclical_coordinate_descent(normalized_simple_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

In [83]:
weights

array([21624999.22590425, 63157245.99915862,        0.        ])

3. Question 3
From the section "Cyclical coordinate descent": Using the simple model (with 2 features), we run our implementation of LASSO coordinate descent on the normalized sales dataset. We apply an L1 penalty of 1e7 and tolerance of 1.0.

Which of the following ranges contains the RSS of the learned model on the normalized dataset?

In [91]:
((np.dot(normalized_simple_feature_matrix, weights) - output) ** 2).sum()

1630492489347445.0

4. Question 4
Refer to the same model as the previous question.

Which of the following features were assigned a zero weight at convergence?

In [92]:
simple_features

['sqft_living', 'bedrooms']

In [93]:
train_data,test_data = sales.random_split(.8,seed=0)

In [96]:
all_features = ['bedrooms',
                'bathrooms',
                'sqft_living',
                'sqft_lot',
                'floors',
                'waterfront', 
                'view', 
                'condition', 
                'grade',
                'sqft_above',
                'sqft_basement',
                'yr_built', 
                'yr_renovated']

In [100]:
(all_feature_matrix, output) = get_numpy_data(train_data, all_features, my_output)
(normalized_all_feature_matrix, all_norms) = normalize_features(all_feature_matrix)

In [103]:
l1_penalty = 1e7
initial_weights = np.zeros(len(all_features) + 1)
tolerance = 1

weights1e7 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

5. Question 5
In the section "Evaluating LASSO fit with more features", we split the data into training and test sets and learn weights with varying degree of L1 penalties. The model now has 13 features.

In the model trained with l1_penalty=1e7, which of the following features has non-zero weight? (Select all that apply)

In [105]:
all_features, weights1e7

(['bathrooms',
  'sqft_living',
  'sqft_lot',
  'floors',
  'waterfront',
  'view',
  'condition',
  'grade',
  'sqft_above',
  'sqft_basement',
  'yr_built',
  'yr_renovated'],
 array([24429601.46249563,        0.        , 48389173.54887038,
               0.        ,        0.        ,  3317511.16160218,
         7329962.03754654,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ]))

In [107]:
l1_penalty = 1e8
initial_weights = np.zeros(len(all_features) + 1)
tolerance = 1

weights1e8 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

6. Question 6
This question refers to the same model as the previous question.

In the model trained with l1_penalty=1e8, which of the following features has non-zero weight? (Select all that apply)

In [109]:
all_features, weights1e8

(['bathrooms',
  'sqft_living',
  'sqft_lot',
  'floors',
  'waterfront',
  'view',
  'condition',
  'grade',
  'sqft_above',
  'sqft_basement',
  'yr_built',
  'yr_renovated'],
 array([71114625.75280938,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ,        0.        ,        0.        ,
               0.        ]))

In [110]:
l1_penalty = 1e4
initial_weights = np.zeros(len(all_features) + 1)
tolerance = 5e5

weights1e4 = lasso_cyclical_coordinate_descent(normalized_all_feature_matrix, output,
                                            initial_weights, l1_penalty, tolerance)

7. Question 7
This question refers to the same model as the previous question.

In the model trained with l1_penalty=1e4, which of the following features has non-zero weight? (Select all that apply)

In [111]:
all_features, weights1e4

(['bathrooms',
  'sqft_living',
  'sqft_lot',
  'floors',
  'waterfront',
  'view',
  'condition',
  'grade',
  'sqft_above',
  'sqft_basement',
  'yr_built',
  'yr_renovated'],
 array([ 77009687.8361678 ,  10676306.89166037,  80738586.07547876,
         -1758165.54210397,  -7617286.17400741,   6726086.809675  ,
          7633304.08223059,  -1431964.5043279 ,  17665648.80328536,
        -10582880.47192084,  -4558009.35268536, -89451187.06017272,
          2771608.8194399 ]))

In [123]:
(feature_matrix, output) = get_numpy_data(train_data, all_features, my_output)
normalized_feature_matrix, norms = normalize_features(feature_matrix)

In [127]:
normalized_weights1e7 = weights1e7 / norms
normalized_weights1e8 = weights1e8 / norms
normalized_weights1e4 = weights1e4 / norms
print normalized_weights1e7

[1.85285539e+05 0.00000000e+00 1.61317454e+02 0.00000000e+00
 0.00000000e+00 2.87664700e+05 6.91937062e+04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00]


In [128]:
(test_feature_matrix, test_output) = get_numpy_data(test_data, all_features, 'price')

In [135]:
RSS_1e4 = ((np.dot(test_feature_matrix, weights1e4) - test_output) ** 2).sum()
RSS_1e7 = ((np.dot(test_feature_matrix, weights1e7) - test_output) ** 2).sum()
RSS_1e8 = ((np.dot(test_feature_matrix, weights1e8) - test_output) ** 2).sum()

8. Question 8
In the section "Evaluating each of the learned models on the test data", we evaluate three models on the test data. The three models were trained with same set of features but different L1 penalties.

Which of the three models gives the lowest RSS on the TEST data?

In [136]:
RSS_1e4, RSS_1e7, RSS_1e8

(4.4649262851494264e+25, 5.0951292434774616e+25, 2.1062423445272723e+19)